### ISSUE TITLE
二维码在终端变形如何处理

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty.js.org#41]
![image](https://user-images.githubusercontent.com/6419514/59408532-d100dd00-8de6-11e9-89ee-76bd9a2b053c.png)

**Comment by caoliang1918** [comment]
这个问题可以换个方式处理，把图片流输出到html，相当于开一个web服务。

**Comment by mongrain** [comment]
I got the same problem.

and now,I use the "qrcode" lib to fix it.

just like that.

```js
const qrcode = require('qrcode')

robot.on('scan', (url, code) => {
    qrcode.toDataURL(url, function (err, base64) {
      var base64Data = base64.replace(/^data:image\/png;base64,/, '')
      fs.writeFile('qrcode/out.png', base64Data, 'base64',
      function (err, data) {
        if (err) {
          console.log('err', err)
        }
      })
    })

    console.log(`Scan QR Code to login: ${code}\n${url}`)
  })
```

then. I got a picture.

![image](https://user-images.githubusercontent.com/22722944/59499310-bc494580-8ec9-11e9-9bb6-9ddcb46f78d7.png)

Maybe it's not a good solution, but it works. 

I wish there was a better way : )

**Comment by huan** [comment]
An alternative way to solve this problem: use our [Wechaty Online QRCode Image Generator](https://github.com/wechaty/qrcode)

```ts
const QRCODE_URL = 'https://wechaty.github.io/qrcode/'
const url = QRCODE_URL + 'https://login.weixin.qq.com/l/YYk19JaKVA=='

console.log(url)
```

Then you can visit the output URL to get the QR Code image.

> https://wechaty.github.io/qrcode/https://login.weixin.qq.com/l/YYk19JaKVA==
