### ISSUE TITLE
Why there is no Chinese document

### ISSUE THREAD

**Issue by isnl** [wechaty/wechaty.js.org#86]
Can I contribute Chinese documents

**Comment by isnl** [comment]
![image](https://user-images.githubusercontent.com/35526117/82029499-ad66a680-96c9-11ea-90a6-7c59b68249f4.png)
I don't know why?

**Comment by su-chang** [comment]
see the right way: https://wechaty.js.org/v/zh/

**Comment by isnl** [comment]
thank you very much! 谢谢您

**Comment by lijiarui** [comment]
@isnl Could you tell me where did you find this link? Thanks!

**Comment by isnl** [comment]
> @isnl Could you tell me where did you find this link? Thanks!

emmm....

It's here！

[https://github.com/wechaty/wechaty.js.org/tree/zh](https://github.com/wechaty/wechaty.js.org/tree/zh)

![image](https://user-images.githubusercontent.com/35526117/82053624-398bc480-96f0-11ea-8fad-8f9e8293b5ce.png)

**Comment by lijiarui** [comment]
fix this! Thanks!
